robpike/ivy

mobile/help.go
mobile/help_gen.go
mobile/mobile.go
mobile/mobile_test.go

for Help menu.
The help page is populated from the robpike.io/ivy package comment
(help_gen.go)
Change-Id: Ieb149b94936f44aa8df9563a0586c28fd9d15ec8

[dev] mobile: add Help function that returns the contents for 'help'

---

config/config.go

Minor patch to ensure different random numbers between runs of `ivy` (e.g. in a script).

Use UnixNano() as seed for random

---

README.md

This PR is heavily inspired by PR #42 (/cc @BDMorrell @robpike), but takes a slightly different approach to improving the formatting. It tries make it render more like the raw markdown text file looks (I hope that's the original intention, but let me know if not).
It also updates the links to use HTTPS scheme and newer canonical address for https://talks.godoc.org.
Finally, this PR is based on `dev` branch rather than `master`, which I understand is the expected way to contribute, based on what @robpike has said in the past.
If merged, this should close #42.

README: update formatting and links

---

talks/script.go

This picks up a dropped error in the `talks` package.

talks: fix dropped error

---

testdata/binary_int.ivy
value/binary.go

x = 1 2 3 4 5
(2 take x), 6 7
x
Because (2 take x) slices x and comma appends,
this was overwriting x to be 1 2 6 7 5.
Fix twice, by making both take and comma trim capacity.

ivy: fix buggy interaction between take and comma

---

testdata/binary_vector.ivy
testdata/exec_fail.ivy
value/binary.go
value/eval.go

Generalized indexing like 'ab'[3 3 rho 1 2] handled a few special cases.
Make it handle all cases, simplifying the code. Also fix a few small
semantic problems in the process.
For example:
Indexing a vector by a vector produces a vector nearly all the time.
This CL changes that to all the time, so that programs can have a
consistent expectation about the rank of the result and whether
it can be indexed. For example, suppose we have a vector of values
and want to extract the positive ones, extract those indexes from
a vector v, and then sort v.
v = v[(x > 0) sel x]
v = v[up v]
(x > 0) sel x is always a vector. If it has length > 1, then v[(x > 0) sel x]
is always a vector. But if it has length == 1, then before this CL,
v[(x > 0) sel x] was a scalar, not a vector, making the indexing in …

ivy: finish generalized indexing, fix shape of index result

---

exec/context.go
testdata/function.ivy

If g is calling f, f should never read or write g's variables.
But that's what Lookup was doing: reading g's variables
instead of globals of the same name. Assignment was correct.
This change factors out the lookup to share it between both.

ivy: fix multi-frame variable lookup bug

---

testdata/unary_bigfloat.ivy
value/log.go

Formerly:
(2 log 8) rho 1
bad shape for rho: (3) is not a small integer

ivy: make logs with integer values be integers

---

ivy_test.go
value/binary.go
value/eval.go
value/matrix.go
value/vector.go

At least for built-in functions, element-wise or row-wise
operations can safely run each element/row in parallel.
This lets Ivy use all of a computer instead of 1 core.
On my 8-physical, 16-logical core MacBook Pro:
```
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' | time ./ivy.old
62625000000
35.34 real        45.45 user         6.66 sys
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' | time ./ivy.new
62625000000
8.27 real        84.08 user         8.75 sys
%
```
I don't believe the doubled user time is real.
It is counting logical-core-user-time, and the two logical cores
are both running and are therefore running at half speed.
That is, using the 16 cores is mostly the same as:
```
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' |  GOMAXPROCS=8 time ./ivy.new
62625000000
8.27 real …
```

ivy: use parallel execution when possible

---

testdata/binary_matrix.ivy
value/matrix.go

This used to crash with a divide-by-zero due to the new
“start in the middle” calculation for the parallel case.
rho transp 1 0 2 rho 0
2 0 1
Don't do that.

ivy: fix divide by zero in parallel binary transp with zero dimension

---

testdata/scan.ivy
value/eval.go

Scan is in general a quadratic operation, but associative operators
(arguably the most useful ones for a scan) can run in linear time instead
by working left-to-right and reusing results, instead of right-to-left.
For example:
+\ iota 100000
runs in a small fraction of a second left-to-right
but takes about 10 minutes right-to-left.
Work left-to-right for known associative operators for speed.

ivy: make scan linear for associative operators

---

config/config.go
run/run.go
run/time_unix.go

Now that ivy can run on multiple CPUs,
it can be interesting to see exactly how
much of the machine is being used.
This commit adds user and system time
to the )debug cpu print, on systems that can.

ivy: print real, user, and system time in )debug cpu

---

value/sin.go

sin, cos, and tan of infinity all looped endlessly inside twoPiReduce.
Partial fix for #98

value: prevent trig function endless loops for infinite argument

---

parse/function.go
parse/save.go
testdata/save.ivy

The new index expression was not accounted for in the
reference walk. This commit adds that.
Also, multiline functions were not followed by a blank line
in the save output, meaning that the output of )save
could not be parsed back with )get. This commit adds a
blank line in )save.
I considered adding a blank line to Function.String,
but that changed the output of )op f to end in two blank lines,
one provided by Function.String and one provided by the
interpreter loop. That seemed like too much, so I put the
special case into )save itself.

ivy: fix )save of new index expression, multiline functions

---

demo_test.go

This fixes the dropped `err` on `ioutil.WriteFile("demo.bad"...)`, adds some constants for `demo.out` and `demo.bad`, and logs when cleanup of `demo.bad` fails.

demo: fix error handling

---

testdata/exec_fail.ivy
value/eval.go

This handles panics for problems like 'division by zero'.
Fixes #103.

ivy: bring panics back to main goroutine in pfor

---

demo/demo.ivy

The op `base` doesn't work properly with numbers that are power of the base.
For example:
```
8 base 2
0 0 0
9 base 3
0 0
```
This is caused by a mismatch between the log operation that return the power and the representation that in this case need a one more number.
This is evident in the op `popcount` that with the powers of two doesn't work:
```
popcount 8
0
popcount 16
0
popcount 32
0
popcount 64
0
```

Fix `base` op example in demo

---

ivy.go

Balance out `f.Create` with an `f.Close`.
Also bail out if `StartCPUProfile` returns a non-`nil` error while here.
I'm not sure if this matters or is helpful, but figured I'd ask by sending this PR.
(Issue golang/go#26970 suggests there may be some benefit.)

ivy: close profile file

---

testdata/statement.ivy
value/bigfloat.go
value/bigint.go
value/bigrat.go

Indexed assignment did not work for rationals, floats, and big integers because in the Copy methods of the types BigRat, BigFloat, and BigInt, relevant variables were not allocated before being used, leading to a nil panic. The following assignments now work:
x = iota 3
x[1] = 1/2
x[2] = float 0.5
x[3] = 10000000000

ivy: fix nil panic on indexed assignment of rationals, floats or big ints

---

parse/function.go
testdata/exec_fail.ivy

Function undefinition did not work because the previous definition was overwritten before being saved, and so restoring it was a no-op.
This meant functions with intermediate state could be produced, potentially violating invariants. For example, the following creates a function with a partial body but without any locals, eventually leading to an index out of range when trying to access the local `b`:
```
op inc b =
b + 1
|
inc 1
```
```
$ ivy <crash.ivy
unexpected EOF
panic: runtime error: index out of range [-1] [recovered]
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
...
```

ivy: fix function undefinition

---

doc.go
mobile/help.go
parse/help.go

The example in the help text about global variables in user-defined operators was lacking the actual operator calls.
Without this line, the described result wouldn't be produced.

ivy: add a missing line in the help text about user-defined operators

---

go.mod

Commit f024fcaf17 uses math/big.Int.Float64 which was introduced in Go version 1.21

Require Go 1.21

---

ivy_test.go

This ensures that tests are independent of the execution order of test files.
Fixes #150

ivy: reset 'maxstack' between test runs

---

value/sys.go

Noticed via
$ go test ./...
value/sys.go:159:25: fmt.Sprint call has possible Printf
formatting directive %d

Fix fmt.Sprint typo

---

value/binary.go
value/const.go
value/matrix.go

These cases are particularly common when operating on large boolean matrices. Avoid significant amounts of garbage allocating zeros and ones.
Commit ded8201e changed zero and one from Value to Int saying "No reason not to, and it takes a few bytes out of the binary". The reason not to is to avoid allocations, so add a comment to that effect.

ivy: optimize away some Int -> Value allocations

---

testdata/unary_matrix.ivy
value/matrix.go

Split was mishandling a matrix with final dimension 0.
Before:
split 1 2 rho iota 2
(1 2)
split 1 1 rho iota 1
(1)
split 1 0 rho iota 0
inconsistent shape ([1]) and data size (0) for new matrix
After:
split 1 2 rho iota 2
(1 2)
split 1 1 rho iota 1
(1)
split 1 0 rho iota 0
()

ivy: fix split of matrix with 0-length dimension

---

parse/parse.go
scan/scan.go
testdata/scan.ivy

Comments in function definitions were disallowed,
even end-of-line comments. I assume this was a bug.
This PR is stacked on others that must be merged first.
To see just the changes specific to this PR when reviewing,
in the "Files Changed" tab, click on "Changes from all commits"
and select just the bottom commit in the list.

ivy: allow comments in function definitions

---

testdata/unary_int.ivy
value/unary.go

The blank line kind of matches interactive mode,
but it is annoying in a long list of debug prints.
This seems wrong:
% {echo 1; echo 2} >x; ivy x
1
2
% {echo print 1; echo print 2} > x; ivy x
1
1
2
2
%
After this CL, there are no blank lines in the second output.
Interactively, before:
% {echo 1; echo 2} | ivy
1
2
% {echo print 1; echo print 2} | ivy
1
1
2
2
%
After:
% {echo print 1; echo print 2} | ivy
1
1
2
2
%
Fixes #177.

ivy: remove extra blank line in print

---

parse/function.go
testdata/function.ivy

Consider:
op f v = x = v; x
op f v = x y = v; x + y
In the first, x is a local variable.
In the second, x and y should be locals as well,
but not handling vector assignment correctly
meant that they were globals instead.
Fix that.
Fixes #176.

ivy: allow vector assignment to declare locals in function

---

exec/context.go
order_test.go
parse/assign.go
parse/function.go
parse/parse.go
parse/save.go
testdata/debug.ivy
value/bigfloat.go
value/bigint.go
value/bigrat.go
value/binary.go
value/char.go
value/complex.go
value/eval.go
value/fac.go
value/format.go
value/index.go
value/int.go
value/matrix.go
value/sets.go
value/sys.go
value/unary.go
value/vector.go

This requires a very large number of mostly mechanical changes,
but now the code does not know that Vector is a slice, which
will allow optimizations like a copy-on-write implementation.
There is more work to do, but this is a large enough change
to be a reasonable checkpoint.

ivy: make Vector an opaque type instead of a slice

---

go.mod
value/eval.go
value/matrix.go

Update to Go 1.23 iterators in Each implementations
and also use slices.Clone in a few places where it makes sense.
This PR is stacked on others that must be merged first.
To see just the changes specific to this PR when reviewing,
in the "Files Changed" tab, click on "Changes from all commits"
and select just the bottom commit in the list.

ivy: update to Go 1.23

---

README.md

hi!
documents that go1.23 is required as of 4ed4c3ebb53371cf22c623ad80bd9f93536b8e62

README.md: bump to go1.23

---

exec/context.go
order_test.go
parse/function.go
parse/save.go
parse/special.go
testdata/copy.ivy
value/assign.go
value/bigfloat.go
value/bigint.go
value/bigrat.go
value/binary.go
value/char.go
value/complex.go
value/const.go
value/context.go
value/eval.go
value/expr.go
value/format.go
value/index.go
value/int.go
value/matrix.go
value/sets.go
value/sys.go
value/unary.go
value/value.go
value/vector.go

This "benchmark" does 10,000 function calls passing an ignored 1000x1000 matrix as an argument.
The old implementation made a copy every time a value was assigned to a variable, making the parameter passing very expensive. The implementation in this CL makes a copy each time modified data is copied out of a variable, eliminating all the copies when the data has not changed (and eliminating the Value.Copy method).
% time ivy0.3.11 testdata/copy.ivy
1000 1000
1000 1000
58.22 real        93.94 user        42.62 sys
% time ivy testdata/copy.ivy
1000 1000
1000 1000
0.27 real         0.04 user         0.01 sys
%
A follow-up change may replace the underlying storage with a more fine-grained copy-on-write tree data structure, but this is already a huge improvement, and it sets up for alternate …

ivy: make vector data immutable, copy-on-write

---

testdata/copy.ivy
value/binary.go
value/persist/slice.go
value/persist/slice_test.go
value/vector.go

APLs traditionally use a reference-counted copy-on-write vector implementation, so that shared vectors are copied before being written, but vectors with only one reference can be written directly.
Getting the reference counts right seems daunting, especially since it would probably require some kind of liveness analysis to make sure dead variables in recursive functions are not holding up references across recursive calls.
Instead, following the example set by Clojure, we can use a persistent data structure, specifically a persistent vector, which is a 16-way tree. Modifying a specific value only has to modify the nodes along the root down to the leaf holding that value, which is only `16 * ceil 16 log n` memory (almost O(1)), not `n` memory (definitely not O(1)).
This provides all the …

ivy: use persistent tree as vector data storage
